### ISSUE TITLE
Dates are not handled correctly

### ISSUE THREAD

**Issue by matsrietdijk** [michaeldyrynda/laravel-nullable-fields#17]
Carbon throws an error when using nullable fields on a date.

**Comment by michaeldyrynda** [comment]
Are you able to provide some sample code to test with, or better yet, a failing test? Which version of Laravel are you using?

**Comment by michaeldyrynda** [comment]
Also, what is the error you're receiving?

**Comment by JacobBennett** [comment]
Here is some info for you

![image](https://cloud.githubusercontent.com/assets/1517011/21407113/96b0cc48-c794-11e6-8843-ebc0397fdd2b.png)

It looks as if when you call the `getAttributes` from the model, it is trying to convert and cast the value to a date with Carbon. This is happening before NullableFields gets a chance to set it as `NULL` which is why it is crashing

**Comment by michaeldyrynda** [comment]
Thanks @JacobBennett, that gives me something to work with. Hopefully I can get to the bottom of this shortly!
